### ISSUE TITLE
local user login fails when http is disabled

### ISSUE THREAD

**Issue by agccie** [agccie/ACI-EnhancedEndpointTracker#16]
workaround for fd exhaustion using local post is to working when https redirect is enabled.  Need to do a few things:
1) change default local proxy from http to https (for app mode can set default to http)
2) disable allow_redirects on requests (since POST is not reposted by default on redirect) 
3) retry on http if https fails.  For app mode this is a repeat of the same post but that's fine as we control the container and this issue should not occur

**Comment by schwabenschulle** [comment]
thank you pulled. My problem seems to be solved.
