### ISSUE TITLE
Does it require to have internet access from APIC to install?

### ISSUE THREAD

**Issue by megazloj** [agccie/ACI-EnhancedEndpointTracker#42]

**Comment by agccie** [comment]
Nope, no internet connection required when running on the APIC.  If you are using syslog  or email notifications then the app will proxy those request through the APIC to the corresponding destinations.  Other than that, the app only performs API reads/subscriptions to the APIC and optional ssh to leafs for clear endpoint (if enabled)

**Comment by megazloj** [comment]
Thank you for detailed answer, @agccie !
It took much time to install, that's why I'd ask. Now it's installed and I'm looking forward to try it out.

Cheers!
